TOKEN = '6820001830:AAEZnj21UcG-rG9FF8RwBqG7WcAZ9ZXkAv8'

LOCAL_WEBHOOK_HOST = '0.0.0.0'
LOCAL_WEBHOOK_PORT = 8080

WEBHOOK_PATH = '/bots/MathBot/webhook'
WEBHOOK_BASE_URL = 'https://orange-weeks-tickle.loca.lt'

WEBHOOK_URL_FULL_PATH = WEBHOOK_BASE_URL + WEBHOOK_PATH
