import os

MODE = os.getenv('MODE')

TOKEN = os.getenv('TOKEN')

LOCAL_WEBHOOK_HOST = os.getenv('LOCAL_WEBHOOK_HOST')
LOCAL_WEBHOOK_PORT = os.getenv('LOCAL_WEBHOOK_PORT')

WEBHOOK_PATH = os.getenv('WEBHOOK_PATH')
WEBHOOK_BASE_URL = os.getenv('WEBHOOK_BASE_URL')

WEBHOOK_URL_FULL_PATH = WEBHOOK_BASE_URL + WEBHOOK_PATH
